spring:
  application:
    name: consumer-frign

server:
  port: 8095
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/ 
      
feign: 
  hystrix: 
    enabled: true   
    
hystrix:
  command: 
    ProviderServer#message(String):  
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 3    
             
      
          