
server:
  port: 7086
  
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka/,http://peer1:8760/eureka/      

spring:
  zipkin:
    base-url: http://localhost:9411    
      